# Makefile for try - Fresh directories for every vibe

SHELL := /bin/bash
RUBY := ruby
SCRIPT := try.rb
TEST_DIR := tests

# Default target
.PHONY: help
help: ## Show this help message
	@echo "try - Fresh directories for every vibe"
	@echo ""
	@echo "Available targets:"
	@grep -E '^[a-zA-Z_-]+:.*?## .*$$' $(MAKEFILE_LIST) | sort | awk 'BEGIN {FS = ":.*?## "}; {printf "  \033[36m%-15s\033[0m %s\n", $$1, $$2}'

.PHONY: test
test: ## Run all tests
	@echo "Running tests..."
	cd $(TEST_DIR) && $(RUBY) -I.. -e "require 'rake'; load 'Rakefile'; Rake::Task['test'].invoke"

.PHONY: test-pr
test-pr: ## Run only PR command tests
	@echo "Running PR command tests..."
	$(RUBY) $(TEST_DIR)/test_pr_command.rb

.PHONY: lint
lint: ## Check Ruby syntax
	@echo "Checking Ruby syntax..."
	$(RUBY) -c $(SCRIPT)
	@for file in $(TEST_DIR)/test_*.rb; do \
		echo "Checking $$file..."; \
		$(RUBY) -c "$$file"; \
	done

.PHONY: dist
dist: dist/try.rb ## Concatenate lib/ + try.rb into dist/try.rb

# One working file: lib/tui.rb, lib/fuzzy.rb, then try.rb (no require_relative).
dist/try.rb: lib/tui.rb lib/fuzzy.rb try.rb
	@mkdir -p dist
	@{ \
	  printf '%s\n' '#!/usr/bin/env ruby'; \
	  printf '%s\n' '# Generated by make dist. Do not edit.'; \
	  printf '%s\n' '# Source: lib/tui.rb + lib/fuzzy.rb + try.rb'; \
	  printf '\n'; \
	  cat lib/tui.rb; \
	  printf '\n'; \
	  cat lib/fuzzy.rb; \
	  printf '\n'; \
	  sed -e '/^#!/d' \
	      -e '/require_relative .lib\/tui./d' \
	      -e '/require_relative .lib\/fuzzy./d' \
	      try.rb; \
	} > dist/try.rb
	@chmod +x dist/try.rb
	@echo "Wrote dist/try.rb"

.PHONY: dist-test
dist-test: dist/try.rb ## Run specs against dist/try.rb
	bash spec/tests/runner.sh dist/try.rb

.PHONY: install
install: dist/try.rb ## Install bin/try + dist/ to ~/.local/
	@echo "Installing try to ~/.local/..."
	@mkdir -p ~/.local/bin ~/.local/dist
	@cp bin/try ~/.local/bin/try
	@chmod +x ~/.local/bin/try
	@cp dist/try.rb ~/.local/dist/try.rb
	@chmod +x ~/.local/dist/try.rb
	@if [ -f dist/try ] && [ -x dist/try ]; then cp dist/try ~/.local/dist/try && chmod +x ~/.local/dist/try; fi
	@echo "Installed! Add ~/.local/bin to PATH, then:"
	@echo "  eval \"\$$(try init ~/src/tries)\""

.PHONY: install-global
install-global: dist/try.rb ## Install bin/try + dist/ to /usr/local/
	@echo "Installing try to /usr/local/..."
	@sudo mkdir -p /usr/local/bin /usr/local/dist
	@sudo cp bin/try /usr/local/bin/try
	@sudo chmod +x /usr/local/bin/try
	@sudo cp dist/try.rb /usr/local/dist/try.rb
	@sudo chmod +x /usr/local/dist/try.rb
	@if [ -f dist/try ] && [ -x dist/try ]; then sudo cp dist/try /usr/local/dist/try && sudo chmod +x /usr/local/dist/try; fi
	@echo "Installed globally! Add to your shell:"
	@echo "  eval \"\$$(try init ~/src/tries)\""

.PHONY: demo
demo: ## Show example commands
	@echo "try - Example commands:"
	@echo ""
	@echo "Basic usage:"
	@echo "  ./$(SCRIPT) --help                                # Show help"
	@echo "  ./$(SCRIPT) init ~/src/tries                     # Generate shell integration"
	@echo ""
	@echo "Clone repositories:"
	@echo "  ./$(SCRIPT) clone https://github.com/user/repo.git"
	@echo "  ./$(SCRIPT) clone git@github.com:user/repo.git my-fork"
	@echo ""
	@echo "Work with PRs:"
	@echo "  ./$(SCRIPT) pr 123                               # PR from current repo"
	@echo "  ./$(SCRIPT) pr user/repo#456                     # PR from specific repo"
	@echo "  ./$(SCRIPT) pr https://github.com/user/repo/pull/789"
	@echo ""
	@echo "Worktrees:"
	@echo "  ./$(SCRIPT) worktree dir                         # From current repo"
	@echo "  ./$(SCRIPT) worktree ~/path/to/repo my-branch    # From specific repo"

.PHONY: version
version: ## Show version information  
	@echo "try.rb - Fresh directories for every vibe"
	@echo "Ruby version: $$($(RUBY) --version)"
	@echo "Script: $(SCRIPT)"

.PHONY: clean
clean: ## Clean up temporary files
	@echo "Cleaning up..."
	@find . -name "*.tmp" -delete
	@find . -name "*~" -delete
	@rm -rf dist
	@echo "Clean complete"

.PHONY: check-deps
check-deps: ## Check for required dependencies
	@echo "Checking dependencies..."
	@command -v $(RUBY) >/dev/null 2>&1 || { echo "Ruby is required but not installed"; exit 1; }
	@echo "✓ Ruby found: $$($(RUBY) --version)"
	@command -v git >/dev/null 2>&1 || { echo "Git is required but not installed"; exit 1; }
	@echo "✓ Git found: $$(git --version)"
	@command -v gh >/dev/null 2>&1 && echo "✓ GitHub CLI found: $$(gh --version | head -1)" || echo "! GitHub CLI not found (optional for PR features)"
	@echo "Dependencies check complete"

.PHONY: dev-setup
dev-setup: check-deps ## Set up development environment
	@echo "Setting up development environment..."
	@echo "All dependencies satisfied"
	@echo ""
	@echo "To test locally:"
	@echo "  make test"
	@echo ""
	@echo "To install locally:"
	@echo "  make install"

.PHONY: all
all: lint test ## Run all checks and tests

# Development shortcuts
.PHONY: t
t: test ## Shortcut for test

.PHONY: l  
l: lint ## Shortcut for lint

.PHONY: i
i: install ## Shortcut for install

# Native binary via Spinel (optional) — compiles the concat, not the split sources
SPINEL ?= spinel
SPINEL_FLAGS ?= -O s
CC ?= cc
NATIVE = dist/try
NATIVE_C = dist/try.c
SPINEL_BIN := $(shell command -v $(SPINEL) 2>/dev/null)
SPINEL_LIB ?= $(dir $(SPINEL_BIN))../lib

.PHONY: native native-test native-compare
native: $(NATIVE)

$(NATIVE_C): dist/try.rb
	mkdir -p dist
	$(SPINEL) $(SPINEL_FLAGS) -c dist/try.rb -o $(NATIVE_C)

$(NATIVE): $(NATIVE_C)
	$(CC) -Os -Wno-all -ffunction-sections -fdata-sections \
		-I$(SPINEL_LIB) -I$(SPINEL_LIB)/regexp \
		$(NATIVE_C) $(SPINEL_LIB)/libspinel_rt.a \
		-lm -lcrypt -Wl,--gc-sections -o $(NATIVE)
	strip $(NATIVE)

native-test: $(NATIVE)
	bash spec/tests/runner.sh $(NATIVE)

native-compare: $(NATIVE)
	bash spec/tests/runner_and_compare.sh dist/try.rb $(NATIVE)
